[build-system]
requires = [
    "setuptools>=61",
    "setuptools_scm[toml]>=7"
]
build-backend = "setuptools.build_meta"

[project]
name = "mqt.predictor"
description = "MQT Predictor - A MQT tool for Determining Good Quantum Circuit Compilation Options"
readme = "README.md"
authors = [
    { name = "Nils Quetschlich", email = "nils.quetschlich@tum.de" },
    { name = "Lukas Burgholzer", email = "lukas.burgholzer@jku.at"},
]
keywords = ["MQT",  "quantum computing", "compilation", "machine learning", "prediction"]
license = { file = "LICENSE" }
requires-python = ">=3.8"
dynamic = ["version"]

dependencies = [
    "qiskit[all]~=0.39.2",
    "pytket~=1.9.0",
    "gym~=0.26.0",
    "stable-baselines3>=1.7.0a0",
    "sb3-contrib~=1.7.0a0",
    "z3-solver~=4.11.0",
    "importlib_resources>=5.0; python_version < '3.10'",
    "numpy~=1.23.5",
    "mqt.bench@ git+https://github.com/cda-tum/MQTbench@dev",
    "matplotlib~=3.5.0",
    "scikit-learn~=1.0.0",
    "natsort~=8.1.0",
    "importlib_resources>=5.9; python_version < '3.10'",
]

classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: MacOS",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Intended Audience :: Science/Research",
    "Natural Language :: English",
    "Topic :: Scientific/Engineering :: Electronic Design Automation (EDA)",
]

[project.optional-dependencies]
test = ["pytest>=7"]
coverage = ["mqt.predictor[test]", "coverage[toml]~=6.5.0", "pytest-cov~=4.0.0"]
dev = ["mqt.predictor[coverage]"]

[project.urls]
Homepage = "https://github.com/cda-tum/mqtpredictor"
"Bug Tracker" = "https://github.com/cda-tum/mqtpredictor/issues"
Discussions = "https://github.com/cda-tum/mqtpredictor/discussions"
Research = "https://www.cda.cit.tum.de/research/quantum/"

[tool.setuptools_scm]


[tool.pytest.ini_options]
filterwarnings = [
    "ignore:Call to deprecated create function FieldDescriptor",
    "ignore:Call to deprecated create function Descriptor",
    "ignore:Call to deprecated create function EnumDescriptor",
    "ignore:Call to deprecated create function EnumValueDescriptor",
    "ignore:Call to deprecated create function FileDescriptor",
    "ignore:Call to deprecated create function OneofDescriptor",
    "ignore:distutils Version classes are deprecated. Use packaging.version instead.",
]
