[build-system]
# Minimum requirements for the build system to execute.
requires = [    "setuptools>=61",
    "setuptools_scm[toml]>=6.4","wheel"]  # PEP 508 specifications.
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
build = "cp3*"
archs = "auto64"
test-command = "python -c \"from mqt import predictor\""
build-verbosity = 3

[tool.cibuildwheel.linux]

[tool.cibuildwheel.macos]

[tool.cibuildwheel.windows]
