name: mac13test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  run:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install MQT Predictor
        run: pip install .
      - name: Generate Report
        run: pytest -v --cov --cov-config=pyproject.toml --cov-report=xml

